version: '3.8'

networks:
  mynet:
    driver: bridge

services:
  bot:
    container_name: telegramBot
    build: .
    ports:
      - 8080:8080
    networks:
      - mynet
    restart: unless-stopped
    depends_on:
      - postgres_db
  postgres_db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hg_bot_config
    ports:
      - 5432:5432
    networks:
      - mynet
    volumes:
      - ./db/init/:/docker-entrypoint-initdb.d
    restart: unless-stopped